# Generated by Django 5.2.10 on 2026-02-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PistolaTorque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_in_charge', models.CharField(max_length=250)),
                ('manufacturer', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=100)),
                ('calibration_cert', models.CharField(max_length=100)),
                ('calibration_number', models.CharField(max_length=100)),
                ('tension_by_manufacturer', models.CharField(max_length=100)),
                ('torque_by_manufacturer', models.CharField(max_length=100)),
                ('giro_number', models.CharField(max_length=50)),
                ('torque_in_field', models.CharField(max_length=150)),
                ('tension_by_test_bench', models.CharField(max_length=150)),
                ('calibration_date', models.DateField()),
                ('calibration_time', models.TimeField()),
                ('serial_number', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entity')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ubication')),
            ],
        ),
    ]
