# Generated by Django 5.2.10 on 2026-03-06 15:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pistolatorque'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPistolaTorque',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('company_in_charge', models.CharField(max_length=250)),
                ('manufacturer', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=100)),
                ('calibration_cert', models.CharField(max_length=100)),
                ('calibration_number', models.CharField(max_length=100)),
                ('tension_by_manufacturer', models.CharField(max_length=100)),
                ('torque_by_manufacturer', models.CharField(max_length=100)),
                ('giro_number', models.CharField(max_length=50)),
                ('torque_in_field', models.CharField(max_length=150)),
                ('tension_by_test_bench', models.CharField(max_length=150)),
                ('calibration_date', models.DateField()),
                ('calibration_time', models.TimeField()),
                ('serial_number', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.entity')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.ubication')),
            ],
            options={
                'verbose_name': 'historical pistola torque',
                'verbose_name_plural': 'historical pistola torques',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
