# Generated by Django 5.2.10 on 2026-03-06 21:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historicalpistolatorque'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPernosVerif',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('color', models.CharField(max_length=150)),
                ('total_campo', models.IntegerField()),
                ('no_cumple_dimens', models.IntegerField()),
                ('presenta_oxido', models.IntegerField()),
                ('hilo_daniado', models.IntegerField()),
                ('tuerca_daniada', models.IntegerField()),
                ('pernos_operativ_total', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.activity')),
                ('equipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.entity')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.ubication')),
            ],
            options={
                'verbose_name': 'historical pernos verif',
                'verbose_name_plural': 'historical pernos verifs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PernosVerif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=150)),
                ('total_campo', models.IntegerField()),
                ('no_cumple_dimens', models.IntegerField()),
                ('presenta_oxido', models.IntegerField()),
                ('hilo_daniado', models.IntegerField()),
                ('tuerca_daniada', models.IntegerField()),
                ('pernos_operativ_total', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entity')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ubication')),
            ],
        ),
    ]
